version: '3.1'

networks:
  micrometer:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - micrometer
    restart: always
    build: prometheus/

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/:/etc/grafana/
    ports:
      - "3000:3000"
    networks:
      - micrometer
    restart: always
    build: grafana/


  spring-app:
    build:
      context: .
    image: spring-boot-prjct-demo:0.1
    ports:
      - "8081:8081"
    networks:
      - micrometer
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/ckkttdhb
      SPRING_DATASOURCE_USERNAME: ckkttdhb
      SPRING_DATASOURCE_PASSWORD: nozrUH1mHHpvvm8s9L_JPAgb1bm14w20
      SPRING_DATASOURCE_HIKARI_SCHEMA: hospital_db
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect


  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ckkttdhb
      POSTGRES_USER: ckkttdhb
      POSTGRES_PASSWORD: nozrUH1mHHpvvm8s9L_JPAgb1bm14w20
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    build: database/


