#        global:
#          scrape_interval: 15s
#
#        scrape_configs:
#          - job_name: 'prometheus'
#            static_configs:
#              - targets: [ 'localhost:9090' ]
#          - job_name: 'spring-boot-prjct'
#            metrics_path: /metrics
#            static_configs:
#              - targets: [ 'host.docker.internal:8080' ]




global:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]
  - job_name: 'spring-boot-prjct'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]







